import type { Metadata } from "next";
import { Urbanist } from 'next/font/google';
import localFont from "next/font/local";
import Navbar from "./ui/Navbar";
import "./globals.css";

const urbanist = Urbanist({
  weight: ['400', '700', '800'],
  subsets: ['latin'],
});

const blanka = localFont({
  src: "./fonts/Blanka.otf",
  variable: "--font-blanka",
  weight: "100 900",
});

export const metadata:Metadata = {
  title: "Mighty Gifs",
  description: "Generated by create next app",
};

function RootLayout({ children }:Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body 
        className={`${urbanist.className} ${blanka.variable} antialiased`}>
        <Navbar />      
        {children}
      </body>
    </html>
  );
}
export default RootLayout;